name: Terraform Apply
on:
  push 
  #schedule:
  #  - cron:  '0 1,13 * * *'
jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Terraform
      env:
        TERRAFORM_VERSION: "0.12.15"
      run: |
        tf_version=$TERRAFORM_VERSION
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip terraform_"$tf_version"_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      env:
        OS_ACCESS_KEY: ${{ secrets.FE_ACCESS_KEY_ID }}
        OS_SECRET_KEY: ${{ secrets.FE_SECRET_ACCESS_KEY }}
        OS_DOMAIN_NAME: ${{ secrets.FE_DOMAIN_NAME }}
        OS_PROJECT_NAME: ${{ secrets.FE_PROJECT_NAME }}
        TF_VAR_KEY_PAIR: ${{ secrets.FE_NETWORK_ID }}
      run: terraform init -input=false

    - name: Terraform validation
      run: terraform validate

    - name: Terraform apply
      env:
        OS_ACCESS_KEY: ${{ secrets.FE_ACCESS_KEY_ID }}
        OS_SECRET_KEY: ${{ secrets.FE_SECRET_ACCESS_KEY }}
        OS_DOMAIN_NAME: ${{ secrets.FE_DOMAIN_NAME }}
        OS_PROJECT_NAME: ${{ secrets.FE_PROJECT_NAME }}
        TF_VAR_VPC_ID: ${{ secrets.FE_VPC_ID }}
        TF_VAR_NETWORK_ID: ${{ secrets.FE_NETWORK_ID }}
      run: |
        echo $TF_VAR_VPC_ID
        terraform apply -auto-approve -input=false -var="vpc_id=$TF_VAR_VPC_ID" -var="subnet_id=$TF_VAR_NETWORK_ID"
      
    - name: Terraform destroy
      env:
        OS_ACCESS_KEY: ${{ secrets.FE_ACCESS_KEY_ID }}
        OS_SECRET_KEY: ${{ secrets.FE_SECRET_ACCESS_KEY }}
        OS_DOMAIN_NAME: ${{ secrets.FE_DOMAIN_NAME }}
        OS_PROJECT_NAME: ${{ secrets.FE_PROJECT_NAME }}
        TF_VAR_VPC_ID: ${{ secrets.FE_VPC_ID }}
        TF_VAR_NETWORK_ID: ${{ secrets.FE_NETWORK_ID }}
      run: terraform destroy -auto-approve -input=false   
